{
  imports = [
    ./acme.nix
    ./adguardhome.nix
    ./atuin-daemon.nix
    ./caddy.nix
    ./forgejo.nix
    ./gitea-actions-runner.nix
    ./komga.nix
    ./mysql.nix
    ./ncps.nix
    ./netbird.nix
    ./ntfy-sh.nix
    ./openssh.nix
    ./radicale.nix
    ./redis.nix
    ./syncthing.nix
    ./traefik.nix
    ./unbound.nix
    ./unifi.nix
    ./vaultwarden.nix
  ];
}
